DealineMVC/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DealineMVC.Models;
namespace DealineMVC.Controllers
{
    [Authorize(Roles = "QuanTri")]
    public class QuanLyDonHangController : Controller
    {
        // GET: QuanLyDonHang
        QuanLyBanHangEntities3 db = new QuanLyBanHangEntities3();
        public ActionResult DaThanhToanChuaGiao()
        {
            //lay ds cac don hang da duyet
            var lst = db.DonDatHangs.Where(n => n.DaThanhToan == true && n.TinhTrangGiaoHang == false);

            return View(lst);
        }
        public ActionResult ChuaGiaoChuaThanhToan()
        {
            //lay ds cac don hang chua giao va chua thanh toan
            var lstDSHCG = db.DonDatHangs.Where(n => n.TinhTrangGiaoHang == false && n.DaThanhToan == false);

            return View(lstDSHCG);
        }
        public ActionResult DaGiaoDaThanhToan()
        {
            //lay ds cac don hang chua giao
            var lstDSHDGDTT = db.DonDatHangs.Where(n => n.TinhTrangGiaoHang == true && n.DaThanhToan == true);

            return View(lstDSHDGDTT);
        }
        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            //ktra id hop le
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang model = db.DonDatHangs.SingleOrDefault(n => n.MaDDH == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            //lay ds chi tiet don hang de hien thi cho nguoi dung
            var lstChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDDH == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(model);
        }
        [HttpPost]
        public ActionResult DuyetDonHang(DonDatHang ddh)
        {
            // truy van lay du lieu cua don hang do
            DonDatHang ddhUpdate = db.DonDatHangs.Single(n => n.MaDDH == ddh.MaDDH);
            ddhUpdate.DaThanhToan = ddh.DaThanhToan;
            ddhUpdate.TinhTrangGiaoHang = ddh.TinhTrangGiaoHang;
            db.SaveChanges();
            //lay ds chi tiet don hang
            var lstChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDDH == ddh.MaDDH);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(ddhUpdate);





        }


    }
}

DealineMVC/Views/QuanLyDonHang/ChuaGiaoChuaThanhToan.cshtml
@model IEnumerable<DealineMVC.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Playout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20); // 1 trang chua 20 sp
}

<h2>Quản lý đơn hàng(Danh sách đơn hàng chưa giao chưa thanh toán)</h2>
<br />
@*tab quanr ly trang thai don hang*@
<ul class="nav nav-tabs">
    <li role="presentation"><a href="@Url.Action("DaThanhToanChuaGiao","QuanLyDonHang")">Thanh toán chưa giao</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("ChuaGiaoChuaThanhToan","QuanLyDonHang")">Chưa giao chưa thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("DaGiaoDaThanhToan","QuanLyDonHang")">Đã giao đã thanh toán</a></li>
</ul>

@grid.GetHtml(
     tableStyle: "gridTable",
     headerStyle: "gridHead",
     footerStyle: "gridFooter",
     rowStyle: "gridRow",
     alternatingRowStyle: "gridAltRow",
     columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn hàng"),
         grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""),
         grid.Column("NgayDat", "Ngày đặt"),
         grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
         grid.Column("NgayGiao", header: "Ngày giao"),
         grid.Column("DaThanhToan", header: "Đã thanh toán"),
         grid.Column("UuDai", header: "Ưu đãi"),
         grid.Column("DaHuy", header: "Đã hủy"),

         grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank" }))

         ))
@*css cho tung style cua table*@
<style>
    .gridTable{
        width:100%;
        border:4px solid #000000;
    }
    .gridTable td {

        border: 1px solid #808080;
    }
    .gridHead {
        background-color:green;
    }
    .gridHead > th > a{
        color:#fff;
    }
    .gridFooter {
        font-weight:bold;
    }

</style>

DealineMVC/Views/QuanLyDonHang/DaGiaoDaThanhToan.cshtml
@model IEnumerable<DealineMVC.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Playout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20); // 1 trang chua 20 sp
}

<h2>Quản lý đơn hàng(Danh sách đơn hàng đã giao đã thanh toán)</h2>
<br />
@*tab quanr ly trang thai don hang*@
<ul class="nav nav-tabs">
    <li role="presentation"><a href="@Url.Action("DaThanhToanChuaGiao","QuanLyDonHang")">Thanh toán chưa giao</a></li>
    <li role="presentation"><a href="@Url.Action("ChuaGiaoChuaThanhToan","QuanLyDonHang")">Chưa giao chưa thanh toán</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan","QuanLyDonHang")">Đã giao đã thanh toán</a></li>
</ul>

@grid.GetHtml(
     tableStyle: "gridTable",
     headerStyle: "gridHead",
     footerStyle: "gridFooter",
     rowStyle: "gridRow",
     alternatingRowStyle: "gridAltRow",
     columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn hàng"),
         grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""),
         grid.Column("NgayDat", "Ngày đặt"),
         grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
         grid.Column("NgayGiao", header: "Ngày giao"),
         grid.Column("DaThanhToan", header: "Đã thanh toán"),
         grid.Column("UuDai", header: "Ưu đãi"),
         grid.Column("DaHuy", header: "Đã hủy"),

         grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank" }))

         ))
@*css cho tung style cua table*@
<style>
    .gridTable{
        width:100%;
        border:4px solid #000000;
    }
    .gridTable td {

        border: 1px solid #808080;
    }
    .gridHead {
        background-color:green;
    }
    .gridHead > th > a{
        color:#fff;
    }
    .gridFooter {
        font-weight:bold;
    }

</style>

DealineMVC/Views/QuanLyDonHang/DaThanhToanChuaGiao.cshtml
@model IEnumerable<DealineMVC.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Playout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20); // 1 trang chua 20 sp
}

<h2>Quản lý đơn hàng(Danh sách đơn hàng đã thanh toán nhưng chưa giao)</h2>
<br />
@*tab quanr ly trang thai don hang*@
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="@Url.Action("DaThanhToanChuaGiao","QuanLyDonHang")">Thanh toán chưa giao</a></li>
    <li role="presentation"><a href="@Url.Action("ChuaGiaoChuaThanhToan","QuanLyDonHang")">Chưa giao chưa thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("DaGiaoDaThanhToan","QuanLyDonHang")">Đã giao đã thanh toán</a></li>
</ul>

@grid.GetHtml(
     tableStyle: "gridTable",
     headerStyle: "gridHead",
     footerStyle: "gridFooter",
     rowStyle: "gridRow",
     alternatingRowStyle: "gridAltRow",
     columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn hàng"),
         grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""),
         grid.Column("NgayDat", "Ngày đặt"),
         grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
         grid.Column("NgayGiao", header: "Ngày giao"),
         grid.Column("DaThanhToan", header: "Đã thanh toán"),
         grid.Column("UuDai", header: "Ưu đãi"),
         grid.Column("DaHuy", header: "Đã hủy"),

         grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank" }))

         ))
@*css cho tung style cua table*@
<style>
    .gridTable{
        width:100%;
        border:4px solid #000000;
    }
    .gridTable td {

        border: 1px solid #808080;
    }
    .gridHead {
        background-color:green;
    }
    .gridHead > th > a{
        color:#fff;
    }
    .gridFooter {
        font-weight:bold;
    }

</style>

DealineMVC/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using DealineMVC.Models;
@model DonDatHang

@{
    ViewBag.Title = "DuyetDonHang";
    Layout = "~/Views/Playout/AdminLayout.cshtml";
}

<h2>Thông tin đơn hàng của <font color="#f65e84">@Model.KhachHang.TenKH</font></h2>
<br />
<br />
@using (Html.BeginForm())
{
    <div class="ChiTietDonHang table">
        @{IEnumerable<ChiTietDonDatHang> lstChiTietDH = (IEnumerable<ChiTietDonDatHang>)ViewBag.ListChiTietDH; }
        <table class="table" id="table">
            @*phan thong tin don hang*@
            <tr>
                <td colspan="4">
                    <table style="width:100%">
                        <tr>
                            <td>Mã đơn hàng <b style="color:red">@Model.MaDDH @Html.Hidden("MaDDH", @Model.MaDDH)</b></td>
                            <td>Mã khách hàng <b style="color:red">@Model.KhachHang.MaKH</b></td>
                            <td>Tên khách hàng <b style="color:red">@Model.KhachHang.TenKH</b></td>
                            <td>Ngày đặt: @Model.NgayDat.Value.ToString("dd/MM/yyyy")</td>
                            <td>Đã thanh toán:@Html.EditorFor(model => model.DaThanhToan)</td>
                            <td>Tình trạng giao hàng:@Html.EditorFor(model => model.TinhTrangGiaoHang)</td>
                        </tr>
                    </table>
                </td>
            </tr>
            @*thong tin chi tiet don hang*@
            <tr>
                <td><b>Sản phẩm</b></td>
                <td><b>Hình ảnh</b></td>
                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>



            </tr>
            @foreach (var item in lstChiTietDH)
            {
                <tr>
                    <td>@item.SanPham.TenSP</td>
                    <td><img width="250" height="200" src="@Url.Content("~/Content/HinhSP/"+item.SanPham.HinhAnh)" /></td>
                    <td>@item.SoLuong</td>
                    <td>@item.DonGia</td>


                </tr>
            }
            <tr>
                <td align="right" colspan="4">Tổng số lượng: @Model.ChiTietDonDatHangs.Sum(n => n.SoLuong) sản phẩm</td>
            </tr>
            <tr>
                <td align="right" colspan="4">Tổng tiền: @Model.ChiTietDonDatHangs.Sum(n => n.SanPham.DonGia).Value.ToString("#,##") đồng</td>
            </tr>

        </table>
        <br /> <br />
        <input type="button" value="In đơn hàng" id="btnInDonHang" />
        <input type="submit" value="Lưu đơn hàng" id="btnLuuDonHang" />
    </div>
}
<script>
    $("#btnInDonHang").click(function () {
        var content = "<table>" +$("#table").html() + "</table>";
        InDonHang(content);

    });
    @*phuong thuc in*@
    function InDonHang(content) {
        var printWindow = window.open('', '', 'height-400,width-800');
        printWindow.document.write('<html><head><title>DIV Contents</title>');
        printWindow.document.write('</head><body>');
        printWindow.document.write(content);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }

</script>